spring:
  application:
    name: subscription-service

  datasource:
    url: jdbc:postgresql://localhost:5432/subscriptiondb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml


  springdoc:
    packages-to-scan: com.example.controller
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG
